name: Build
on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
         name: build_files
         path: dist
    
      